language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
install:
  - pip install .
  - pip install -r requirements/requirements-all.txt
  - pip install -r requirements/requirements-test.txt  
#script: pytest --remote-data --cov=refgenconf
script:
  - echo "skipping tests"
branches:
  only:
    - dev
    - master
