language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
install:
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-all.txt
  - pip install -r requirements/requirements-test.txt
script:
  - echo "skipping tests"
branches:
  only:
    - dev
    - master