site_name: Refgenie
site_logo: img/refgenie_logo_light.svg
site_url: http://refgenie.databio.org/
repo_url: http://github.com/databio/refgenie
pypi_name: refgenie

nav:
  - Getting Started: 
    - Introduction: README.md
    - Installing refgenie: install.md
    - Use cases: use-cases.md
    
  - How-to guides:
    - Manage local assets: local.md
    - Download pre-built assets: download.md
    - Build genome assets: build.md
    - Use refgenie from python: refgenconf.md
    - Use external assets: external_assets.md
    - Run my own server: refgenieserver.md
  - Reference:
    - Python API: autodoc_build/refgenconf.md
    - Genome confuration file: genome_config.md
    - Recipes: recipes.md
    - Usage: usage.md
    - FAQ: faq.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
- databio:
    autodoc_build: "docs/autodoc_build"
    autodoc_package: "refgenconf"
    no_top_level: true
- search
