site_name: Refgenie
site_logo: img/refgenie_logo_light.svg
site_url: http://refgenie.databio.org/
repo_url: http://github.com/databio/refgenie
pypi_name: refgenie

nav:
  - Getting Started: 
    - Introduction: README.md
    - Installing: install.md
    - Hello world: hello-world.md
    - Use cases: use-cases.md
    
  - How-to guides:    
    - Download pre-built indexes: download.md
    - Installing genome indexers: install_indexers.md
    - Build genome indexes: build.md
  - Reference:
    - Recipes: recipes.md
    - Usage: usage.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio
  - search
