site_name: Refgenie
site_logo: img/refgenie_logo_light.svg
site_url: http://refgenie.databio.org/
repo_url: http://github.com/databio/refgenie
pypi_name: refgenie

nav:
  - Getting Started: 
    - Introduction: README.md
    - Overview: overview.md
    - Install and configure: install.md
  - How-to guides:
    - Download pre-built assets: pull.md
    - Use custom genomes: build.md
    - Retrieve paths to assets: seek.md
    - Use refgenie from python: refgenconf.md
    - Use refgenie with iGenomes: igenomes.md
    - Use custom assets: custom_assets.md
    - Run my own asset server: refgenieserver.md
  - Reference:
    - Genome configuration file: genome_config.md
    - Glossary: glossary.md
    - Usage: usage.md
    - Python API: autodoc_build/refgenconf.md
    - FAQ: faq.md
    - Support: https://github.com/databio/refgenie/issues
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
- databio:
    autodoc_build: "docs/autodoc_build"
    autodoc_package: "refgenconf"
    no_top_level: true
- search


navbar:
  left:
  - text: Refgenomes server
    icon: fa-server
    href: http://refgenomes.databio.org