name: Test refgenie CLI

on:
  push:
    branches: [master, dev]

jobs:
  test_CLI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dev dependancies
      run: if [ -f requirements/requirements-dev.txt ]; then pip install -r requirements/requirements-dev.txt; fi

    - name: Install package
      run: python -m pip install .

    - name: install macOS-specific dependancies
      if: startsWith(matrix.os, 'macOS')
      run: brew install md5sha1sum

    - name: create genomes dir
      run: mkdir genomes

    - name: refgenie init
      working-directory: ./genomes
      run: refgenie init -c g.yaml; cat g.yaml

    - name: refgenie list
      working-directory: ./genomes
      run: refgenie list -c g.yaml

    - name: refgenie build fasta (parent asset)
      run: |
        refgenie build -c genomes/g.yaml t7/fasta --files fasta=tests/data/t7.fa.gz --recipe  tests/data/recipe_parent.json
        ./tests/assert_in_file.sh genomes/g.yaml t7 0
        ./tests/assert_in_file.sh genomes/g.yaml fde5c225d75637d6b2fd463a37ff875d 0 # this is a digest that should be produced from this FASTA file

    - name: refgenie build fasta_child (child asset)
      run: |
        refgenie build -c genomes/g.yaml t7/fasta_child --recipe tests/data/recipe_child.json
        ./tests/assert_in_file.sh genomes/g.yaml fasta_child 0

    - name: refgenie list
      working-directory: ./genomes
      run: refgenie list -c g.yaml

    - name: refgenie remove fasta_child
      run: |
        refgenie remove -c genomes/g.yaml t7/fasta_child -f
        ./tests/assert_in_file.sh genomes/g.yaml fasta_child 1
        ./tests/assert_in_file.sh genomes/g.yaml fde5c225d75637d6b2fd463a37ff875d/fasta_child:default 1 # test if the entry was removed from the fasta children list

    - name: refgenie remove fasta, leave digest
      run: |
        refgenie remove -c genomes/g.yaml t7/fasta -f
        ./tests/assert_in_file.sh genomes/g.yaml fasta 1
        ./tests/assert_in_file.sh genomes/g.yaml fde5c225d75637d6b2fd463a37ff875d 0

    - name: refgenie build fasta
      run: refgenie build -c genomes/g.yaml t7/fasta --files fasta=refgenie/tests/data/t7.fa.gz --recipe refgenie/tests/data/recipe_parent.json

    - name: refgenie remove fasta, remove digest
      run: |
        refgenie remove -c genomes/g.yaml t7/fasta -f -a
        ./tests/assert_in_file.sh genomes/g.yaml fasta 1
        ./tests/assert_in_file.sh genomes/g.yaml fde5c225d75637d6b2fd463a37ff875d 1